Change which for command -v, inside POSIX library & smell changes
softwaresano/pipeline_plugin pull request #59
Opened 2021-06-04 09:09 UTC by pag-telf

2021-06-04 09:12 UTC, carlosegg requested changes

2021-06-04 09:12 UTC, carlosegg commented on plugin/app/plugins/pipeline_plugin/tools/scm/git/templates/hooks/validators/yaml.sh
> +  if [[ $(command -v ruby) ]]; then
command -v ruby  &>/dev/null && validate_ruby || validate_yamlint

2021-06-04 09:12 UTC, carlosegg commented on plugin/app/plugins/pipeline_plugin/tools/scm/git/templates/hooks/pre-commit
> +  FILE_NAME=$1
ERRRORR file_name se lo has pasado como parámetro, no hay que ponerlo en mayusculas

2021-06-04 09:20 UTC, pag-telf commented on plugin/app/plugins/pipeline_plugin/tools/scm/git/templates/hooks/pre-commit
> +  FILE_NAME=$1
Se pone como mayúsculas para poder referenciarlo en los hooks, sino `shellcheck` se queja

2021-06-04 09:28 UTC, pag-telf commented on plugin/app/plugins/pipeline_plugin/tools/scm/git/templates/hooks/validators/yaml.sh
> +  if [[ $(command -v ruby) ]]; then
a shellcheck no le gusta la estructura A && B || C

2021-06-09 15:05 UTC, carlosegg requested changes

2021-06-09 15:05 UTC, carlosegg commented on plugin/app/plugins/pipeline_plugin/tools/scm/git/templates/hooks/pre-commit
> +  local FILE_NAME
este no hace falta tocarlo es un parámetro que le estás pasando

2021-08-06 06:43 UTC, closed without merging